In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
filepath = '/content/drive/MyDrive/PatternRecognition/'

"""
Datacsv from https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-L01-v3_1.html
"""

#Colab用
"""vpath = "L01-2023P-2K.csv"
pl_df = pd.read_csv(filepath+vpath,encoding="SHIFT_JIS")
"""
#ローカル用
vpath = "L01-2023P-48-01.0a/L01-2023P-2K.csv"
pl_df = pd.read_csv(vpath,encoding="SHIFT_JIS")

In [ ]:
print(pl_df.columns.values)

['経度' '緯度' '所在地コード' '用途' '連番' '年次' '前年所在地コード' '前年用途' '前年連番' '市区町村名'
 '所在並びに地番' '住居表示' '行政' '地積' '利用の現況' '利用状況表示' '利用区分' '建物構造' '施設' '形状区分'
 '間口（比率）' '奥行（比率）' '階層（地上）' '階層（地下）' '前面道路区分' '前面道路の方位区分' '前面道路の幅員'
 '前面道路の駅前区分' '前面道路の舗装状況' '側道区分' '側道方位区分' '交通施設との近接区分' '周辺の土地の利用の現況' '駅名'
 '駅距離' '用途区分' '防火区分' '都市計画区分' '高度地区' '森林区分' '公園区分' '建蔽率' '容積率' '割増容積率'
 '共通地点区分' '対前年変動率' '選定年次ビット' 'Ｓ５８価格' 'Ｓ５９価格' 'Ｓ６０価格' 'Ｓ６１価格' 'Ｓ６２価格'
 'Ｓ６３価格' 'Ｈ１価格' 'Ｈ２価格' 'Ｈ３価格' 'Ｈ４価格' 'Ｈ５価格' 'Ｈ６価格' 'Ｈ７価格' 'Ｈ８価格' 'Ｈ９価格'
 'Ｈ１０価格' 'Ｈ１１価格' 'Ｈ１２価格' 'Ｈ１３価格' 'Ｈ１４価格' 'Ｈ１５価格' 'Ｈ１６価格' 'Ｈ１７価格' 'Ｈ１８価格'
 'Ｈ１９価格' 'Ｈ２０価格' 'Ｈ２１価格' 'Ｈ２２価格' 'Ｈ２３価格' 'Ｈ２４価格' 'Ｈ２５価格' 'Ｈ２６価格' 'Ｈ２７価格'
 'Ｈ２８価格' 'Ｈ２９価格' 'Ｈ３０価格' 'Ｈ３１価格' 'Ｒ２価格' 'Ｒ３価格' 'Ｒ４価格' 'Ｒ５価格' '属性移動Ｓ５９'
 '属性移動Ｓ６０' '属性移動Ｓ６１' '属性移動Ｓ６２' '属性移動Ｓ６３' '属性移動Ｈ１' '属性移動Ｈ２' '属性移動Ｈ３'
 '属性移動Ｈ４' '属性移動Ｈ５' '属性移動Ｈ６' '属性移動Ｈ７' '属性移動Ｈ８' '属性移動Ｈ９' '属性移動Ｈ１０' '属性移動Ｈ１１'
 '属性移動Ｈ１２' '属性移動Ｈ１３' '属性移動Ｈ１４' '属性移動Ｈ１５' '属性移動Ｈ１６' '属性移動Ｈ１７' '属性移動Ｈ１８'
 '属性移動Ｈ１９' '属性移動Ｈ２０' '属性移動Ｈ２１' '属性移動Ｈ２２' '属性移動Ｈ２３' '属性移動Ｈ２４' '属性移動Ｈ２５'
 '属性移動

In [ ]:

colm = ['所在地コード', '用途', '連番', '年次', '前年所在地コード', '前年用途', '前年連番', '市区町村名', '所在並びに地番', '住居表示', '行政', '地積', '利用の現況', '利用状況表示', '利用区分', '建物構造', '施設', '形状区分', '間口（比率）', '奥行（比率）', '階層（地上）', '階層（地下）', '前面道路区分', '前面道路の方位区分', '前面道路の幅員', '前面道路の駅前区分', '前面道路の舗装状況', '側道区分', '側道方位区分', '交通施設との近接区分', '周辺の土地の利用の現況', '駅名', '駅距離', '用途区分', '防火区分', '都市計画区分', '高度地区', '森林区分', '公園区分', '建蔽率', '容積率', '割増容積率', '共通地点区分', '対前年変動率', '選定年次ビット', 'Ｓ５８価格', 'Ｓ５９価格', 'Ｓ６０価格', 'Ｓ６１価格', 'Ｓ６２価格', 'Ｓ６３価格', 'Ｈ１価格', 'Ｈ２価格', 'Ｈ３価格', 'Ｈ４価格', 'Ｈ５価格', 'Ｈ６価格', 'Ｈ７価格', 'Ｈ８価格', 'Ｈ９価格', 'Ｈ１０価格', 'Ｈ１１価格', 'Ｈ１２価格', 'Ｈ１３価格', 'Ｈ１４価格', 'Ｈ１５価格', 'Ｈ１６価格', 'Ｈ１７価格', 'Ｈ１８価格', 'Ｈ１９価格', 'Ｈ２０価格', 'Ｈ２１価格', 'Ｈ２２価格', 'Ｈ２３価格', 'Ｈ２４価格', 'Ｈ２５価格', 'Ｈ２６価格', 'Ｈ２７価格', 'Ｈ２８価格', 'Ｈ２９価格', 'Ｈ３０価格', 'Ｈ３１価格', 'Ｒ２価格', 'Ｒ３価格', 'Ｒ４価格', '属性移動Ｓ５９', '属性移動Ｓ６０', '属性移動Ｓ６１', '属性移動Ｓ６２', '属性移動Ｓ６３', '属性移動Ｈ１', '属性移動Ｈ２', '属性移動Ｈ３', '属性移動Ｈ４', '属性移動Ｈ５', '属性移動Ｈ６', '属性移動Ｈ７', '属性移動Ｈ８', '属性移動Ｈ９', '属性移動Ｈ１０', '属性移動Ｈ１１', '属性移動Ｈ１２', '属性移動Ｈ１３', '属性移動Ｈ１４', '属性移動Ｈ１５', '属性移動Ｈ１６', '属性移動Ｈ１７', '属性移動Ｈ１８', '属性移動Ｈ１９', '属性移動Ｈ２０', '属性移動Ｈ２１', '属性移動Ｈ２２', '属性移動Ｈ２３', '属性移動Ｈ２４', '属性移動Ｈ２５', '属性移動Ｈ２６', '属性移動Ｈ２７', '属性移動Ｈ２８', '属性移動Ｈ２９', '属性移動Ｈ３０', '属性移動Ｈ３１', '属性移動Ｒ２', '属性移動Ｒ３', '属性移動Ｒ４', '属性移動Ｒ５']
pl_df = pl_df.drop(columns = colm)
array = ['緯度','経度','Ｈ２１価格']

pl_df.head(2)
#pl_df = pl_df.reindex(index=['緯度','経度','Ｈ２１価格'])
datalist = pl_df.values
datalist[:,:2] /= 3600

print(datalist[:40])
#0:経度 1:緯度 2:公示地価

[[1.41314045e+02 4.30554489e+01 4.18000000e+05]
 [1.41339397e+02 4.30418089e+01 1.95000000e+05]
 [1.41344557e+02 4.30471300e+01 1.83000000e+05]
 [1.41349443e+02 4.30363600e+01 2.12000000e+05]
 [1.41315303e+02 4.30438969e+01 6.00000000e+04]
 [1.41330166e+02 4.30759500e+01 1.47000000e+05]
 [1.41347921e+02 4.30206319e+01 1.30000000e+05]
 [1.41319415e+02 4.30409181e+01 1.25000000e+05]
 [1.41303756e+02 4.30560219e+01 1.99000000e+05]
 [1.41294764e+02 4.30566519e+01 1.11000000e+05]
 [1.41342544e+02 4.30277750e+01 1.76000000e+05]
 [1.41322718e+02 4.30525481e+01 2.82000000e+05]
 [1.41352104e+02 4.30406769e+01 2.35000000e+05]
 [1.41327251e+02 4.30675669e+01 2.14000000e+05]
 [1.41299611e+02 4.30496700e+01 1.02000000e+05]
 [1.41327962e+02 4.30359039e+01 7.20000000e+04]
 [1.41331896e+02 4.30525539e+01 2.35000000e+05]
 [1.41324553e+02 4.30408419e+01 1.81000000e+05]
 [1.41304433e+02 4.30609911e+01 2.39000000e+05]
 [1.41339313e+02 4.30370111e+01 2.06000000e+05]
 [1.41334723e+02 4.30618689e+01 2.920000

In [ ]:
%pip install segment-geospatial leafmap localtileserver > /dev/null 2>&1

In [ ]:
import os
import leafmap
from samgeo import SamGeo, show_image, download_file, overlay_images, tms_to_geotiff
import pyproj
from PIL import Image, TiffImagePlugin

sur = 0.005 #取得範囲
zoom = 16 #１７で保存するといい感じ（経度によるwidthの歪みがあるのでリサイズ必須）
siz = 512  #リサイズ

imagepathlist = []
images = []
for i in range(len(datalist)): #40をlen(datalist)
    m = leafmap.Map(center=[datalist[i,0],datalist[i,1] ], zoom=20, height="800px")
    m.add_basemap(f"SATELLITE{i}")
    bbox = [datalist[i,0]-sur,datalist[i,1]-sur ,datalist[i,0]+sur, datalist[i,1]+sur]
    #image = f"{filepath}/images/satellite{str(i).zfill(6)}.tif"
    #ローカル用
    image = f"images/satellite{str(i).zfill(6)}.tif"
    imagepathlist.append(image)
    tms_to_geotiff(output=image, bbox=bbox, zoom=zoom, source="Satellite", overwrite=True)
    img = Image.open(image)
    img = img.resize((siz,siz))
    img.save(image)
    img = np.array(img)
    images.append(img)
    imagepathlist.append(image)

images = np.stack(images)

imagepathlist = np.array(imagepathlist)
chika = datalist[:,2]
print(images.shape) #衛星画像
print(chika.shape)   #地価
np.save('images.npy', images)
np.save('chika.npy', chika)
